const DATA_POOL_DIRECTORY = '../data-pool/data/';
const TITLES_FILE = 'titles.json';
const CONTENT_FILE = 'content.json';
const TAGS_FILE = 'tags.json';
const AMOUNT_DATA_PER_FILE = 100;
const MAX_SIZE_TITLE = 2000;
const MAX_SIZE_TAG_NAME = 191;
const FILES_OF_DATA = [TITLES_FILE, CONTENT_FILE, TAGS_FILE]

module.exports = {DATA_POOL_DIRECTORY, TITLES_FILE, CONTENT_FILE, TAGS_FILE, AMOUNT_DATA_PER_FILE, MAX_SIZE_TITLE, MAX_SIZE_TAG_NAME, FILES_OF_DATA}
